export default {
    // Navigation
    arrowLeft:      'arrow-left',
    arrowRight:     'arrow-right',
    arrowUp:        'arrow-up',
    arrowDown:      'arrow-down',
    chevronLeft:    'chevron-left',
    chevronRight:   'chevron-right',
    chevronUp:      'chevron-up',
    chevronDown:    'chevron-down',
    home:           'home',
    menu:           'menu-2',
    close:          'x',
    back:           'arrow-back',
    forward:        'arrow-forward',
    expand:         'arrows-maximize',
    collapse:       'arrows-minimize',
    fullscreen:     'maximize',
    fullscreenExit: 'minimize',

    // Actions
    search:         'search',
    filter:         'filter',
    sort:           'arrows-sort',
    edit:           'pencil',
    delete:         'trash',
    add:            'plus',
    remove:         'minus',
    save:           'device-floppy',
    copy:           'copy',
    download:       'download',
    upload:         'upload',
    share:          'share',
    refresh:        'refresh',
    more:           'dots',
    settings:       'settings',
    drag:           'grip-horizontal',
    resize:         'resize',
    undo:           'arrow-back-up',
    redo:           'arrow-forward-up',
    scan:           'scan',
    print:          'printer',
    import:         'file-import',
    export:         'file-export',

    // Feedback
    check:          'check',
    checkCircle:    'circle-check',
    error:          'circle-x',
    warning:        'alert-triangle',
    info:           'info-circle',
    help:           'help-circle',
    loading:        'loader-2',
    success:        'circle-check',

    // User
    user:           'user',
    userCircle:     'user-circle',
    users:          'users',
    lock:           'lock',
    unlock:         'lock-open',
    eye:            'eye',
    eyeOff:         'eye-off',
    bell:           'bell',
    notification:   'bell-ringing',

    // Files & Media
    file:           'file',
    folder:         'folder',
    image:          'photo',
    document:       'file-text',
    attachment:     'paperclip',
    link:           'link',
    externalLink:   'external-link',
    play:           'player-play',
    pause:          'player-pause',
    stop:           'player-stop',
    mute:           'volume-off',
    sound:          'volume',
    video:          'video',
    camera:         'camera',

    // Interface
    grid:           'layout-grid',
    list:           'list',
    calendar:       'calendar',
    clock:          'clock',
    tag:            'tag',
    tags:           'tags',
    qrCode:         'qrcode',
    barcode:        'barcode',

    // Text editing
    bold:           'bold',
    italic:         'italic',
    underline:      'underline',
    strikethrough:  'strikethrough',
    alignLeft:      'align-left',
    alignCenter:    'align-center',
    alignRight:     'align-right',
    alignJustify:   'align-justified',
    orderedList:    'list-numbers',
    unorderedList:  'list',
    indent:         'indent-increase',
    outdent:        'indent-decrease',
    scissors:       'scissors',
    fontColor:      'letter-case',
    highlight:      'highlight',

    // Data & charts
    barChart:       'chart-bar',
    lineChart:      'chart-line',
    pieChart:       'chart-pie',
    areaChart:      'chart-area',
    table:          'table',
    database:       'database',

    // Commerce & finance
    shoppingCart:   'shopping-cart',
    creditCard:     'credit-card',
    wallet:         'wallet',
    bank:           'building-bank',
    gift:           'gift',
    percentage:     'percentage',
    dollar:         'currency-dollar',
    euro:           'currency-euro',

    // Communication
    mail:           'mail',
    message:        'message',
    comment:        'message-circle',
    phone:          'phone',

    // System & dev
    cloud:          'cloud',
    cloudUpload:    'cloud-upload',
    cloudDownload:  'cloud-download',
    api:            'api',
    code:           'code',
    bug:            'bug',
    tool:           'tool',
    robot:          'robot',

    // Location
    map:            'map',
    compass:        'compass',
    global:         'world',
    location:       'map-pin',

    // Shapes & objects
    star:           'star',
    heart:          'heart',
    flag:           'flag',
    trophy:         'trophy',
    medal:          'medal',
    rocket:         'rocket',
    fire:           'flame',
    thunder:        'bolt',
    smile:          'mood-smile',
    frown:          'mood-sad',
    like:           'thumb-up',
    dislike:        'thumb-down',
    safety:         'shield-check',
    key:            'key',
};
