/**
 * Google Material Icons — ligature names.
 * The icon name IS the ligature text content of the element.
 * Names use snake_case as defined by Google.
 */
export default {
    // Navigation
    arrowLeft:      'arrow_back',
    arrowRight:     'arrow_forward',
    arrowUp:        'arrow_upward',
    arrowDown:      'arrow_downward',
    chevronLeft:    'chevron_left',
    chevronRight:   'chevron_right',
    chevronUp:      'expand_less',
    chevronDown:    'expand_more',
    home:           'home',
    menu:           'menu',
    close:          'close',
    back:           'arrow_back',
    forward:        'arrow_forward',
    expand:         'open_in_full',
    collapse:       'close_fullscreen',
    fullscreen:     'fullscreen',
    fullscreenExit: 'fullscreen_exit',

    // Actions
    search:         'search',
    filter:         'filter_list',
    sort:           'sort',
    edit:           'edit',
    delete:         'delete',
    add:            'add',
    remove:         'remove',
    save:           'save',
    copy:           'content_copy',
    download:       'download',
    upload:         'upload',
    share:          'share',
    refresh:        'refresh',
    more:           'more_horiz',
    settings:       'settings',
    drag:           'drag_indicator',
    resize:         'open_with',
    undo:           'undo',
    redo:           'redo',
    scan:           'qr_code_scanner',
    print:          'print',
    import:         'file_upload',
    export:         'file_download',

    // Feedback
    check:          'check',
    checkCircle:    'check_circle',
    error:          'error',
    warning:        'warning',
    info:           'info',
    help:           'help',
    loading:        'sync',
    success:        'task_alt',

    // User
    user:           'person',
    userCircle:     'account_circle',
    users:          'group',
    lock:           'lock',
    unlock:         'lock_open',
    eye:            'visibility',
    eyeOff:         'visibility_off',
    bell:           'notifications',
    notification:   'notification_important',

    // Files & Media
    file:           'insert_drive_file',
    folder:         'folder',
    image:          'image',
    document:       'description',
    attachment:     'attach_file',
    link:           'link',
    externalLink:   'open_in_new',
    play:           'play_arrow',
    pause:          'pause',
    stop:           'stop',
    mute:           'volume_off',
    sound:          'volume_up',
    video:          'videocam',
    camera:         'camera_alt',

    // Interface
    grid:           'grid_view',
    list:           'list',
    calendar:       'calendar_today',
    clock:          'access_time',
    tag:            'label',
    tags:           'label',
    qrCode:         'qr_code',
    barcode:        'barcode_reader',

    // Text editing
    bold:           'format_bold',
    italic:         'format_italic',
    underline:      'format_underlined',
    strikethrough:  'strikethrough_s',
    alignLeft:      'format_align_left',
    alignCenter:    'format_align_center',
    alignRight:     'format_align_right',
    alignJustify:   'format_align_justify',
    orderedList:    'format_list_numbered',
    unorderedList:  'format_list_bulleted',
    indent:         'format_indent_increase',
    outdent:        'format_indent_decrease',
    scissors:       'content_cut',
    fontColor:      'format_color_text',
    highlight:      'highlight',

    // Data & charts
    barChart:       'bar_chart',
    lineChart:      'show_chart',
    pieChart:       'pie_chart',
    areaChart:      'area_chart',
    table:          'table_chart',
    database:       'storage',

    // Commerce & finance
    shoppingCart:   'shopping_cart',
    creditCard:     'credit_card',
    wallet:         'account_balance_wallet',
    bank:           'account_balance',
    gift:           'card_giftcard',
    percentage:     'percent',
    dollar:         'attach_money',
    euro:           'euro',

    // Communication
    mail:           'mail',
    message:        'message',
    comment:        'comment',
    phone:          'phone',

    // System & dev
    cloud:          'cloud',
    cloudUpload:    'cloud_upload',
    cloudDownload:  'cloud_download',
    api:            'api',
    code:           'code',
    bug:            'bug_report',
    tool:           'build',
    robot:          'smart_toy',

    // Location
    map:            'map',
    compass:        'explore',
    global:         'language',
    location:       'location_on',

    // Shapes & objects
    star:           'star',
    heart:          'favorite',
    flag:           'flag',
    trophy:         'emoji_events',
    medal:          'military_tech',
    rocket:         'rocket_launch',
    fire:           'local_fire_department',
    thunder:        'bolt',
    smile:          'sentiment_satisfied',
    frown:          'sentiment_dissatisfied',
    like:           'thumb_up',
    dislike:        'thumb_down',
    safety:         'verified_user',
    key:            'key',
};
