export default {
    // Navigation
    arrowLeft:      'arrow-left',
    arrowRight:     'arrow-right',
    arrowUp:        'arrow-up',
    arrowDown:      'arrow-down',
    chevronLeft:    'caret-left',
    chevronRight:   'caret-right',
    chevronUp:      'caret-up',
    chevronDown:    'caret-down',
    home:           'house',
    menu:           'list',
    close:          'x',
    back:           'arrow-left',
    forward:        'arrow-right',
    expand:         'arrows-out',
    collapse:       'arrows-in',
    fullscreen:     'arrows-out-simple',
    fullscreenExit: 'arrows-in-simple',

    // Actions
    search:         'magnifying-glass',
    filter:         'funnel',
    sort:           'arrows-down-up',
    edit:           'pencil-simple',
    delete:         'trash',
    add:            'plus',
    remove:         'minus',
    save:           'floppy-disk',
    copy:           'copy',
    download:       'download-simple',
    upload:         'upload-simple',
    share:          'share-network',
    refresh:        'arrows-clockwise',
    more:           'dots-three',
    settings:       'gear-six',
    drag:           'dots-six-vertical',
    resize:         'corners-out',
    undo:           'arrow-counter-clockwise',
    redo:           'arrow-clockwise',
    scan:           'scan',
    print:          'printer',
    import:         'upload',
    export:         'export',

    // Feedback
    check:          'check',
    checkCircle:    'check-circle',
    error:          'x-circle',
    warning:        'warning',
    info:           'info',
    help:           'question',
    loading:        'circle-notch',
    success:        'check-circle',

    // User
    user:           'user',
    userCircle:     'user-circle',
    users:          'users',
    lock:           'lock',
    unlock:         'lock-open',
    eye:            'eye',
    eyeOff:         'eye-slash',
    bell:           'bell',
    notification:   'bell-ringing',

    // Files & Media
    file:           'file',
    folder:         'folder',
    image:          'image',
    document:       'file-text',
    attachment:     'paperclip',
    link:           'link',
    externalLink:   'arrow-square-out',
    play:           'play',
    pause:          'pause',
    stop:           'stop',
    mute:           'speaker-slash',
    sound:          'speaker-high',
    video:          'video',
    camera:         'camera',

    // Interface
    grid:           'squares-four',
    list:           'list',
    calendar:       'calendar',
    clock:          'clock',
    tag:            'tag',
    tags:           'tag',
    qrCode:         'qr-code',
    barcode:        'barcode',

    // Text editing
    bold:           'text-b',
    italic:         'text-italic',
    underline:      'text-underline',
    strikethrough:  'text-strikethrough',
    alignLeft:      'text-align-left',
    alignCenter:    'text-align-center',
    alignRight:     'text-align-right',
    alignJustify:   'text-align-justify',
    orderedList:    'list-numbers',
    unorderedList:  'list-bullets',
    indent:         'text-indent',
    outdent:        'text-outdent',
    scissors:       'scissors',
    fontColor:      'text-aa',
    highlight:      'highlighter-circle',

    // Data & charts
    barChart:       'chart-bar',
    lineChart:      'chart-line',
    pieChart:       'chart-pie',
    areaChart:      'chart-line-up',
    table:          'table',
    database:       'database',

    // Commerce & finance
    shoppingCart:   'shopping-cart',
    creditCard:     'credit-card',
    wallet:         'wallet',
    bank:           'bank',
    gift:           'gift',
    percentage:     'percent',
    dollar:         'currency-dollar',
    euro:           'currency-eur',

    // Communication
    mail:           'envelope',
    message:        'chat-text',
    comment:        'chat',
    phone:          'phone',

    // System & dev
    cloud:          'cloud',
    cloudUpload:    'cloud-arrow-up',
    cloudDownload:  'cloud-arrow-down',
    api:            'plugs',
    code:           'code',
    bug:            'bug',
    tool:           'wrench',
    robot:          'robot',

    // Location
    map:            'map-trifold',
    compass:        'compass',
    global:         'globe',
    location:       'map-pin',

    // Shapes & objects
    star:           'star',
    heart:          'heart',
    flag:           'flag',
    trophy:         'trophy',
    medal:          'medal',
    rocket:         'rocket',
    fire:           'fire',
    thunder:        'lightning',
    smile:          'smiley',
    frown:          'smiley-melting',
    like:           'thumbs-up',
    dislike:        'thumbs-down',
    safety:         'shield-check',
    key:            'key',
};
